name: ML Pipeline with MLflow and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 1: Prepare Data
      - name: Prepare Data
        run: make prepare

      # Step 2: Train the Model
      - name: Train Model
        run: make train

      # Step 3: Evaluate the Model
      - name: Evaluate Model
        run: make evaluate

      # Step 4: Set up MLflow
      - name: Create MLruns Directory
        run: mkdir -p mlruns

      # Step 5: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t my-ml-app .

      # Step 6: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.Aziz7905 }}
          password: ${{ secrets.222JMT4622 }}

      # Step 7: Tag Docker Image
      - name: Tag Docker Image
        run: |
          docker tag my-ml-app ${{ secrets.Aziz7905 }}/my-ml-app:latest

      # Step 8: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/my-ml-app:latest

      - name: Run Docker Container
        run: |
          docker run -d --name ml_app -p 5000:5000 -p 5001:5001 -p 5002:5002 my-ml-app

      # Step 9: Start MLflow Server
      - name: Start MLflow Server with SQLite Backend
        run: |
          docker exec -d ml_app mlflow server \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root file://$(pwd)/mlruns \
            --host 0.0.0.0 \
            --port 5002
          sleep 10

      # Step 10: Start FastAPI apps (app.py and app1.py)
      - name: Start app.py on port 5000
        run: |
          docker exec -d ml_app uvicorn app:app --host 0.0.0.0 --port 5000
          sleep 5

      - name: Start app1.py on port 5001
        run: |
          docker exec -d ml_app uvicorn app1:app --host 0.0.0.0 --port 5001
          sleep 5


      # Step 12: Upload MLflow Logs
      - name: Upload MLflow Logs
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns/
